# Generated by Django 6.0.2 on 2026-03-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(help_text='The original task description provided by the user.')),
                ('prompt', models.TextField(help_text='The generated prompt template.')),
                ('variables', models.JSONField(default=list, help_text='List of variable names extracted from the prompt.')),
                ('raw_response', models.TextField(blank=True, default='', help_text='Raw metaprompt response (for debugging).')),
                ('is_improved', models.BooleanField(default=False, help_text='Whether this prompt was improved from an existing one.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Prompt Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
