# Generated by Django 5.2.12 on 2026-03-29 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompthistory',
            name='analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Structured task analysis (goal, audience, tone, format, constraints).'),
        ),
        migrations.AddField(
            model_name='prompthistory',
            name='draft_prompt',
            field=models.TextField(blank=True, default='', help_text='First-pass generated prompt before improvement.'),
        ),
        migrations.AddField(
            model_name='prompthistory',
            name='score',
            field=models.FloatField(blank=True, help_text='Quality score from the evaluation system (1-10).', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AddField(
            model_name='prompthistory',
            name='score_details',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed scoring breakdown by criteria.'),
        ),
        migrations.AddField(
            model_name='prompthistory',
            name='task_type',
            field=models.CharField(choices=[('blog', 'Blog / Content'), ('coding', 'Coding / Development'), ('agent', 'Agent / Automation'), ('general', 'General')], default='general', help_text='Classified task category.', max_length=20),
        ),
        migrations.AddField(
            model_name='prompthistory',
            name='user_feedback',
            field=models.TextField(blank=True, default='', help_text='Free-text feedback from the user.'),
        ),
        migrations.AddField(
            model_name='prompthistory',
            name='user_rating',
            field=models.IntegerField(blank=True, help_text='User satisfaction rating (1-5 stars).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='prompthistory',
            name='version',
            field=models.IntegerField(default=1, help_text='Number of improvement passes applied.'),
        ),
        migrations.AlterField(
            model_name='prompthistory',
            name='prompt',
            field=models.TextField(help_text='The final (best) generated prompt template.'),
        ),
    ]
