# Generated by Django 5.2.12 on 2026-03-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_pipeline_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompthistory',
            name='latency_ms',
            field=models.IntegerField(blank=True, help_text='Total time taken by the pipeline in milliseconds.', null=True),
        ),
        migrations.AddField(
            model_name='prompthistory',
            name='parent_prompt_id',
            field=models.IntegerField(blank=True, help_text='Lineage tracking: ID of the prompt this was improved from.', null=True),
        ),
        migrations.AddField(
            model_name='prompthistory',
            name='tokens_used',
            field=models.IntegerField(blank=True, help_text='Total LLM tokens consumed during pipeline execution.', null=True),
        ),
    ]
