# Generated by Django 5.2.12 on 2026-03-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_prompthistory_latency_ms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompthistory',
            name='task_type',
            field=models.JSONField(default=list, help_text="List of classified task categories (e.g. ['blog', 'coding'])."),
        ),
    ]
